server:
  port: 8080
  forward-headers-strategy: native
spring:
  application:
    name: back
  web:
    resources:
      static-locations: classpath:/static/
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: dev
  output:
    ansi:
      enabled: always
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    hikari:
      auto-commit: false
  jackson:
    serialization:
      fail-on-empty-beans: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never

custom:
  dev:
    cookieDomain: localhost
    frontUrl: http://${custom.dev.cookieDomain}:3000
    backUrl: http://${custom.dev.cookieDomain}:${server.port}
  prod:
    cookieDomain: game.everyknu.com
    frontUrl: https://www.${custom.prod.cookieDomain}
    backUrl: https://api.${custom.prod.cookieDomain}
  site:
    cookieDomain: "${custom.dev.cookieDomain}"
    frontUrl: "${custom.dev.frontUrl}"
    backUrl: "${custom.dev.backUrl}"
    name: nutree
  jwt:
    secretKey: ${CUSTOM__JWT__SECRET_KEY}
  accessToken:
    expirationSeconds: "#{60*20}"

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    doc-expansion: none
    operations-sorter: alpha
    tags-sorter: alpha
    try-it-out-enabled: true
    filter: true
    display-request-duration: true